services:
  homepage:
    image: ghcr.io/cagataygurturk/homepage:cpp
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/cagataygurturk/homepage:cpp
    networks:
      - app-network
    ports:
      - 8080:8080
    environment:
      - PORT=8080

networks:
  app-network:
    driver: bridge