apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
- namespace.yaml
- deployment.yaml
- loadbalancer.yaml

labels:
- includeSelectors: true
  pairs:
    app: homepage

